/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AnimeAnimIdImport } from './routes/anime.$animId'

// Create Virtual Routes

const HomeLazyImport = createFileRoute('/Home')()
const AboutLazyImport = createFileRoute('/About')()

// Create/Update Routes

const HomeLazyRoute = HomeLazyImport.update({
  path: '/Home',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/Home.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/About',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/About.lazy').then((d) => d.Route))

const AnimeAnimIdRoute = AnimeAnimIdImport.update({
  path: '/anime/$animId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/About': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/Home': {
      preLoaderRoute: typeof HomeLazyImport
      parentRoute: typeof rootRoute
    }
    '/anime/$animId': {
      preLoaderRoute: typeof AnimeAnimIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AboutLazyRoute,
  HomeLazyRoute,
  AnimeAnimIdRoute,
])

/* prettier-ignore-end */
